[package]
name = "pinner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { version = "2.0.9", features = ["rustls", "ws"] }
tokio = { version = "1.32.0", features = [
    "rt",
    "rt-multi-thread",
    "macros",
] } # Ethers' async features rely upon the Tokio async runtime.
# Flexible concrete Error Reporting type built on std::error::Error with customizable Reports
eyre = "0.6.8"
config = "0.13.3"
clap = { version = "4.4.1", features = ["derive"] }
foundry-contracts = { path = "../bindings" }
